DO NOT MERGE: Issue 082: Automate and Refactor the Order on Behalf Of Experience
sfb2csolutionarchitects/b2c-crm-sync pull request #115
Opened 2021-06-01 10:49 UTC by b2csolutionarchitect

... see #82 for details.  Some of the feedback we've received regarding the OOBO / assisted shopping experience is that the setup is complex, brittle, and requires extensive documentation.  With this PR, we're tried to simplify the setup through automation as well as re-imagine the Service Agent experience.

> Please do-not merge this pull request until it has gone through the review process.  We've refactored a TON of code here, and I expect the review to provide another round of refactored changes.  

- The B2C Instance setup is now 100% command-line driven and repeatable
- We've added UI elements to the shopping experience denoting that an Agent is logged in
- We've introduced new management quick-actions for the B2C Instance, CustomerList, and Site objects in the Salesforce Platform to activate / de-activate them quickly
- We've introduced new CLI commands to create and synchronize the OOBO configuration settings between B2C Commerce and the Salesforce Platform

There are still manual configuration steps that need to be performed.  This should dramatically simplify the process, however, and allow users to setup OOBO without the nuanced complexity of the previous install.  Please review the updated readMe.md for details.

2021-06-01 13:51 UTC, jbachelet commented on lib/apis/sfdc/flow/_postB2CInstanceSetup.js
> +        return resolve(output);
`return` is useless

2021-06-01 13:51 UTC, jbachelet commented on lib/apis/sfdc/flow/_postB2CInstanceSetup.js
> +        return reject(e);
here too

2021-06-01 13:51 UTC, jbachelet commented on lib/apis/sfdc/flow/_postB2CInstanceSetup.js
> +    const headers = {
this could directly be added to the `requestConfig` object without creating a temp variable:
```
requestConfig = {
    headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-cache',
        Connection: 'keep-alive',
        Authorization: `Bearer ${authToken}`
    }
};
```

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_b2cOCAPIConfigGet.js
> +                for (let ocapiConfig of ocapiConfigResults.global[0].site_configs) {
```
output.outputDisplay.global = ocapiConfigResults.global[0].site_configs.map(ocapiConfig => {
    return [ocapiConfig.api_type, JSON.stringify(ocapiConfig, null, 4)];
});
```

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_b2cOCAPIConfigGet.js
> +                for (let ocapiConfig of ocapiConfigResults.sites) {
output.outputDisplay.sites = ocapiConfigResults.sites.map(ocapiConfig => {
    // Replace the identifiers from the site_id in the OCAPI config
    siteId = ocapiConfig.site_id.replace('Sites-', '').replace('-Site', '');

    // Build the site-specific output display
    return [siteId, JSON.stringify(ocapiConfig, null, 4)];
});

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_b2cOOBOCustomersCreate.js
> +    for (let thisSite of verifiedSites) {
```
output = verifiedSites
    .filter(thisSite => !customerLists.hasOwnProperty(thisSite.data.customerList))
    .map(thisSite => {
        // Capture the result of the profile creation / verification process
        customerProfileResult = await b2cOOBOCustomerCreate(environmentDef, thisSite);
        // Flag that the customerList has been processed
        customerLists[thisSite.data.customerList] = customerProfileResult;
        return customerProfileResult;
    });
```

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_b2cOOBOCustomersVerify.js
> +    for (let thisSite of verifiedSites) {
same as the previous comment

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_b2cOOBOSitePrefsGet.js
> +        for (let thisSite of verifiedSites) {
same loop changes as previous comments

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_b2cOOBOSitePrefsUpdate.js
> +        for (let thisSite of verifiedSites) {
same as previous comments

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_common/_auditOCAPIConfig.js
> +    filePath = config.get('paths.source.dx.config').toString() + '/' + fileName;
```
const path = require('path');

filePath = [config.get('paths.source.dx.config').toString(), fileName].join(path.sep);
```

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_sfB2CInstanceGet.js
> +module.exports = (environmentDef) => {
```
module.exports = environmentDef => sfdx.data.recordGet({
    sobjecttype: 'B2C_Instance__c',
    where: `Name='${environmentDef.b2cInstanceName}'`
});
```

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_sfOOBOB2CSitesReset.js
> +module.exports = async (environmentDef, customerList) => {
no promise returned here?

2021-06-01 13:51 UTC, jbachelet commented on lib/cli-api/_sfOOBOB2CSitesUpdate.js
> +module.exports = async (environmentDef, customerProfile) => {
no promise returned here?

2021-06-01 13:51 UTC, jbachelet commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/scripts/hooks/session.js
> +'use strict';
Do you think it make sense to move this into the regular cartridge instead of the skin one?

2021-06-01 13:51 UTC, jbachelet commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/pageHeader.isml
> +<header>
please don't override the `pageHeader` template, instead leverage the existing `app.template.beforeHeader` hook to inject your agentHeader template on top of SFRA: https://github.com/SalesforceCommerceCloud/storefront-reference-architecture/blob/master/cartridges/app_storefront_base/cartridge/templates/default/common/layout/page.isml#L19

2021-06-01 13:51 UTC, jbachelet commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/agentHeader.isml
> +<isscript>
Please don't use `isscript` tags. As you'll leverage the hook to inject your template, please move all of this within a script file, and leverage the `Template.render()` method to render your template (https://documentation.b2c.commercecloud.salesforce.com/DOC2/topic/com.demandware.dochelp/DWAPI/scriptapi/html/api/class_dw_util_Template.html#dw_util_Template_render_Map_DetailAnchor)

2021-06-01 13:51 UTC, jbachelet commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/pageHeaderNomenu.isml
> +<header>
this override won't be needed anymore when you'll leverage the hook

2021-06-01 13:51 UTC, jbachelet commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/pdStorePageHeader.isml
> +<header>
this override won't be needed anymore when you'll leverage the hook

2021-06-05 01:16 UTC, b2csolutionarchitect commented on lib/_common/request/_createOCAPIAuthRequestDef.js
> +    output = addBasicAuthHeader(output, authCredentialBase64);
... thank you; see [f603c851b](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/f603c851b6577630520e138b2689f750da2f5b30) for details.

2021-06-05 01:19 UTC, b2csolutionarchitect commented on lib/apis/sfdc/flow/_postB2CInstanceSetup.js
> +        return resolve(output);
... thank you; see [ec32cd0a](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/ec32cd0a1cd9f4f79c40ea6ed79dd30c1083ddb8) for details.

2021-06-05 01:20 UTC, b2csolutionarchitect commented on lib/apis/sfdc/flow/_postB2CInstanceSetup.js
> +        return reject(e);
... thank you; see [ec32cd0a](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/ec32cd0a1cd9f4f79c40ea6ed79dd30c1083ddb8) for details.

2021-06-05 01:23 UTC, b2csolutionarchitect commented on lib/apis/sfdc/flow/_postB2CInstanceSetup.js
> +    const headers = {
... thank you; see [152e01535](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/152e015358943d9acb5d6fa28ec57f40f5f73a74) for details.

2021-06-05 16:56 UTC, b2csolutionarchitect commented on lib/cli-api/_b2cOCAPIConfigGet.js
> +                for (let ocapiConfig of ocapiConfigResults.global[0].site_configs) {
... thank you; see [d768b30b43c](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/d768b30b43c0b41072a89fba250b023c2e3509aa) for details.

2021-06-05 17:03 UTC, b2csolutionarchitect commented on lib/cli-api/_b2cOCAPIConfigGet.js
> +                for (let ocapiConfig of ocapiConfigResults.sites) {
... thank you; see [d6484683a](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/d6484683a1d6daddd34431c0c684f6c800f56cbc) for details.

2021-06-05 17:48 UTC, b2csolutionarchitect commented on lib/cli-api/_b2cOOBOCustomersCreate.js
> +    for (let thisSite of verifiedSites) {
... ok; couldn't get this working -- the async / await pairing math didn't work.  Leaving as-is -- but happy to revisit.

2021-06-05 17:48 UTC, b2csolutionarchitect commented on lib/cli-api/_b2cOOBOCustomersVerify.js
> +    for (let thisSite of verifiedSites) {
... same here; couldn't get this working -- the async / await pairing math didn't work. Leaving as-is -- but happy to revisit.

2021-06-05 17:51 UTC, b2csolutionarchitect commented on lib/cli-api/_common/_auditOCAPIConfig.js
> +    filePath = config.get('paths.source.dx.config').toString() + '/' + fileName;
... thank you; see [ead5b823a](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/ead5b823a668b9ae74f5b665821153933f85824a) for details.

2021-06-05 17:53 UTC, b2csolutionarchitect commented on lib/cli-api/_sfB2CInstanceGet.js
> +module.exports = (environmentDef) => {
... thank you; see [0dc5fa022ba](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/0dc5fa022ba548733de2cf7498428e8fc0a88653) for details.

2021-06-05 19:03 UTC, b2csolutionarchitect commented on lib/cli-api/_sfOOBOB2CSitesReset.js
> +module.exports = async (environmentDef, customerList) => {
... thank you; see [8d7b18cc](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/8d7b18cc5b9b9e6c111700fd89d5cad2e6c89b1d) for details.

2021-06-05 19:08 UTC, b2csolutionarchitect commented on lib/cli-api/_sfOOBOB2CSitesUpdate.js
> +module.exports = async (environmentDef, customerProfile) => {
... thank you; see [8d7b18cc](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/8d7b18cc5b9b9e6c111700fd89d5cad2e6c89b1d) for details.

2021-06-05 19:09 UTC, b2csolutionarchitect commented on lib/cli-api/_b2cOOBOSitePrefsGet.js
> +        for (let thisSite of verifiedSites) {
... same here; couldn't get this working -- the async / await pairing math didn't work. Leaving as-is -- but happy to revisit.

2021-06-05 19:09 UTC, b2csolutionarchitect commented on lib/cli-api/_b2cOOBOSitePrefsUpdate.js
> +        for (let thisSite of verifiedSites) {
... same here; couldn't get this working -- the async / await pairing math didn't work. Leaving as-is -- but happy to revisit.

2021-06-05 19:13 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/scripts/hooks/session.js
> +'use strict';
... you know, I was thinking about this -- and I think we should keep it in a separate cartridge so that you could "remove" the skin cartridge if you don't want any of the OOBO / storefront use-case stuff.  I think if we include in the regular cartridge this hook could get implemented without the need.  I think it's more obvious to deduce "I don't want any of the UI stuff -- so let's not deploy the skin" vs. having to document files to cherry-pick out of the existing plugin cartridge.  Maybe we rename the cartridge "plugin_b2ccrmsync_oobo" to make it more clear?

2021-06-05 19:32 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/scripts/hooks/session.js
> +'use strict';
... renamed the cartridge to follow the plugin model; see [20e8d0feac](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/20e8d0feac585c25e69bd1adf9d1731eecd1b688) for details.

2021-06-05 22:52 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/pageHeader.isml
> +<header>
... thank you for the direction; see [aa66a31834f](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/aa66a31834f0254255156a10cd9694d032813d67) for details.

2021-06-05 22:53 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/agentHeader.isml
> +<isscript>
... thank you for the direction; see [aa66a31834f](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/aa66a31834f0254255156a10cd9694d032813d67) for details.

2021-06-05 22:53 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/pdStorePageHeader.isml
> +<header>
... thank you for the direction; see [aa66a31834f](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/aa66a31834f0254255156a10cd9694d032813d67) for details.

2021-06-05 22:53 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/skin_b2ccrmsync/cartridge/templates/default/components/header/pageHeaderNomenu.isml
> +<header>
... thank you for the direction; see [aa66a31834f](https://github.com/sfb2csolutionarchitects/b2c-crm-sync/pull/115/commits/aa66a31834f0254255156a10cd9694d032813d67) for details.

2021-06-06 14:23 UTC, b2csolutionarchitect commented
@jbachelet -- please review; I made the edits that I could and also worked through a handful of related additional issues.  Please pay close attention to the refactor of the skin cartridge to the oobo plugin.  I'm injecting the header -- but not certain if the pattern I employed is the best one.  As always, thank you for your efforts -- looking forward to your feedback.

2021-06-07 13:34 UTC, jbachelet requested changes

2021-06-07 13:34 UTC, jbachelet commented on src/sfcc/cartridges/plugin_b2ccrmsync_oobo/cartridge/templates/default/components/header/agentOOBOHeader.isml
> +                <isif condition="${pdict.customerNo.length > 0}">
you don't need to check for existence when using `isprint`

2021-06-07 16:38 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/plugin_b2ccrmsync_oobo/cartridge/templates/default/components/header/agentOOBOHeader.isml
> +                <isif condition="${pdict.customerNo.length > 0}">
... ok; fixed!

2021-06-07 16:38 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/plugin_b2ccrmsync_oobo/cartridge/templates/default/components/header/agentOOBOHeader.isml
> +<div class="bg-danger pt-1 pb-1">
Fixed!  Thank you for the call-out.

2021-06-07 16:39 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/plugin_b2ccrmsync_oobo/cartridge/templates/default/components/header/agentOOBOHeader.isml
> +                    ${Resource.msg('agentheader.customerno','b2ccrmsync',null)}
Ok -- I compromised; I added the default to the .js script -- and simplified the rendering of the template.  We need defaults to test the headerLayout outside of the agent context (ex. I want to make simple UI changes).

2021-06-07 16:39 UTC, b2csolutionarchitect commented on src/sfcc/cartridges/plugin_b2ccrmsync_oobo/cartridge/templates/default/components/header/agentOOBOHeader.isml
> +                  ${Resource.msg('agentheader.customername','b2ccrmsync',null)}
Ok -- I compromised; I added the default to the .js script -- and simplified the rendering of the template.  We need defaults to test the headerLayout outside of the agent context (ex. I want to make simple UI changes).

2021-06-07 16:40 UTC, merged