issue 022 : added duration days env variable
sfb2csolutionarchitects/b2c-crm-sync pull request #23
Opened 2021-04-08 20:28 UTC by sandragolden

issue 022 : added duration days as an .env variable to make the number of days a scratchOrg will live configurable prior to deployment.

Please let me know if anything was mixed or needs to be adjusted.

2021-04-09 14:48 UTC, jbachelet requested changes

2021-04-09 14:48 UTC, jbachelet commented on lib/cli-api/_common/_getScratchOrgDurationDays.js
> +module.exports = getScratchOrgDurationDays;
I would suggest the following version of the function:

```suggestion
module.exports = scratchOrgDurationDays => validators.validateDurationDays(scratchOrgDurationDays).validationResult === true ? scratchOrgDurationDays : config.get('sfScratchOrg.durationDays');
```

2021-04-09 15:42 UTC, sandragolden commented on lib/cli-api/_common/_getScratchOrgDurationDays.js
> +module.exports = getScratchOrgDurationDays;
updated, much cleaner, thanks!

2021-04-11 03:10 UTC, b2csolutionarchitect commented on lib/cli-api/_common/_getScratchOrgDurationDays.js
> +module.exports = getScratchOrgDurationDays;
Thank you @sandragolden and @jbachelet!  You're making history. :)

2021-04-11 03:14 UTC, b2csolutionarchitect approved these changes
... nice work @sandragolden; real curious to get your feedback re: extending the CLI framework we're leveraging.  Thank you for your efforts!

2021-04-11 03:14 UTC, b2csolutionarchitect commented on lib/cli-api/_common/_getScratchOrgDurationDays.js
> +module.exports = getScratchOrgDurationDays;
... and by the way, @jbachelet did the EXACT SAME THING to me.

2021-04-11 03:14 UTC, merged